/*
 * rcc.c
 *
 *  Created on: Jan 4, 2025
 *      Author: benjamin
 */


#include "rcc.h"

void initRCC(){

	reset();
	enable();


}

void reset(){
	//GPIO
	RCC_AHB1RSTR |=  RCC_AHB1RSTR_GPIOARST;//GPIOA
	//USART
	RCC_APB1RSTR|= RCC_APB1RSTR_USART2RST;//USART2
	//TIM
	RCC_APB1RSTR|=RCC_APB1RSTR_TIM2RST//TIM2
	//SYSCFG
	RCC_APB2RSTR|= RCC_APB2RSTR_SYSCFGRST;//SYSCFG
	//ADC
	RCC_APB2RSTR|= RCC_APB2RSTR_ADCRST;//ADC
}

void enable(){
	//GPIO
	RCC_AHB1ENR|= RCC_AHB1ENR_GPIOAEN;//GPIOA
	//USART
	RCC_APB1ENR|= RCC_APB1ENR_USART2EN;//USART2
	//TIM
	RCC_APB1ENR|=RCC_APB1ENR_TIM2EN;//TIM2
	//SYSCFG
	RCC_APB2ENR|= RCC_APB2ENR_SYSCFGEN;
	//ADC
	RCC_APB2ENR|=RCC_APB2ENR_ADC1EN;

}
