/*
 * rcc.c
 *
 *  Created on: Jan 4, 2025
 *      Author: benjamin
 */


#include "rcc.h"

void initRCC(){

	//reset();
	enable();


}

void reset(){
	//GPIO
	RCC->AHB1RSTR &= ~(RCC_AHB1RSTR_GPIOARST |RCC_AHB1RSTR_GPIOBRST);//reset GPIOA and GPIOB
	RCC->AHB1RSTR |= (RCC_AHB1RSTR_GPIOARST |RCC_AHB1RSTR_GPIOBRST);
	//USART
	RCC->APB1RSTR&= ~RCC_APB1RSTR_USART2RST;//USART2
	RCC->APB1RSTR|= RCC_APB1RSTR_USART2RST;//USART2
	//TIM
	RCC->APB1RSTR&= ~RCC_APB1RSTR_TIM2RST;//TIM2
	RCC->APB1RSTR |= RCC_APB1RSTR_TIM2RST;
	//SYSCFG
	RCC->APB2RSTR&= ~RCC_APB2RSTR_SYSCFGRST;//SYSCFG
	RCC->APB2RSTR|= RCC_APB2RSTR_SYSCFGRST;
	//ADC
	RCC->APB2RSTR&= ~RCC_APB2RSTR_ADCRST;//ADC
	RCC->APB2RSTR|= RCC_APB2RSTR_ADCRST;
}

void enable(){
	RCC->AHB1ENR=0;
	RCC->APB1ENR=0;
	RCC->APB2ENR=0;
	//GPIO
	RCC->AHB1ENR|= RCC_AHB1ENR_GPIOAEN;
	//USART
	RCC->APB1ENR|= RCC_APB1ENR_USART2EN;
	//TIM
	RCC->APB1ENR|=RCC_APB1ENR_TIM2EN;//TIM2
	//SYSCFG
	RCC->APB2ENR|= RCC_APB2ENR_SYSCFGEN;
	//ADC
	RCC->APB2ENR|=RCC_APB2ENR_ADC1EN;

}
